version: 2
workdir: internal
allow:
  depOnAnyVendor: false

excludeFiles:
  - "^.*_test\\.go$"

vendors:
  go-modfile:
    in: golang.org/x/mod/modfile
  go-packages:
    in: golang.org/x/tools/go/packages
  3rd-cobra:
    in: github.com/spf13/cobra
  3rd-yaml:
    in:
      - github.com/goccy/go-yaml
      - github.com/goccy/go-yaml/parser
  3rd-color-fmt:
    in: github.com/logrusorgru/aurora/v3
  3rd-code-highlight:
    in: github.com/alecthomas/chroma/*
  3rd-json-scheme:
    in: github.com/xeipuuv/gojsonschema

components:
  container:
    in: app/internal/container/**
  app:
    in: app

  commands:
    in: commands/*

  glue:
    in: glue/**
  glueCode:
    in: glue/code
  glueProject:
    in: glue/project/**
  gluePrinter:
    in: glue/printer
  glueSpec:
    in: glue/spec/**
  glueYamlSpec:
    in: glue/yaml/spec
  glueYaml:
    in: glue/yaml/*

  models:
    in: models/**
  schema:
    in: schema
  services:
    in: services/*
  version:
    in: version
  view:
    in: view

commonComponents:
  - models

deps:
  container:
    anyProjectDeps: true
    anyVendorDeps: true

  app:
    mayDependOn:
      - container
      - version

  commands:
    canUse:
      - 3rd-cobra

  glueSpec:
    mayDependOn:
      - glueYamlSpec

  glueYaml:
    mayDependOn:
      - glueYamlSpec
    canUse:
      - 3rd-yaml

  glueYamlSpec:
    canUse:
      - 3rd-yaml
      - 3rd-json-scheme

  glueProject:
    canUse:
      - go-modfile
      - go-packages

  gluePrinter:
    canUse:
      - 3rd-color-fmt

  glueCode:
    canUse:
      - 3rd-code-highlight
