version: 3
workdir: internal
allow:
  depOnAnyVendor: false

excludeFiles:
  - "^.*_test\\.go$"
  - "^.*\/test\/.*$"

vendors:
  go-common:           { in: golang.org/x/sync/errgroup }
  go-ast:              { in: [ golang.org/x/mod/modfile, golang.org/x/tools/go/packages ] }
  3rd-cobra:           { in: github.com/spf13/cobra }
  3rd-color-fmt:       { in: github.com/logrusorgru/aurora/v3 }
  3rd-code-highlight:  { in: github.com/alecthomas/chroma/* }
  3rd-json-scheme:     { in: github.com/xeipuuv/gojsonschema }
  3rd-graph:           { in: oss.terrastruct.com/d2/** }
  3rd-yaml:
    in:
      - github.com/goccy/go-yaml
      - github.com/goccy/go-yaml/**
      - github.com/fe3dback/go-yaml    # custom fork (need propose back PR)
      - github.com/fe3dback/go-yaml/** # custom fork (need propose back PR)

components:
  main:                { in: app }
  container:           { in: app/internal/container/** }
  operations:          { in: operations/* }
  services:            { in: services/** }
  view:                { in: view }
  models:              { in: models/** }

commonVendors:
  - go-common

commonComponents:
  - models

deps:
  main:
    mayDependOn:
      - container

  container:
    anyVendorDeps: true
    mayDependOn:
      - operations
      - services
      - view

  operations:
    mayDependOn:
      - services
    canUse:
      - 3rd-graph

  services:
    mayDependOn:
      - services
    canUse:
      - go-ast
      - 3rd-yaml
      - 3rd-color-fmt
      - 3rd-code-highlight
      - 3rd-json-scheme
