version: 4
workingDirectory: internal

settings:
  imports:
    strictMode: false
    allowAnyVendorImports: false
  structTags:
    allowed: [json]

exclude:
  files:
    - "^.*_test\\.go$"
    - "^.*\/test\/.*$"
    - "^.*\/tests\/.*$"
    - "^.*\/mocks\/.*$"

vendors:
  sdk-models:          { in: github.com/fe3dback/go-arch-lint-sdk/arch }
  sdk-commands:        { in:
                            - github.com/fe3dback/go-arch-lint-sdk
                            - github.com/fe3dback/go-arch-lint-sdk/commands/*
                       }
  sdk-libs:            { in: github.com/fe3dback/go-arch-lint-sdk/pkg/** }
  go-x-libs:           { in: golang.org/x/** }
  cli:                 { in: github.com/urfave/cli/v2 }
  cli-term-libs:       { in:
                            - github.com/muesli/termenv
                       }

components:
  main:                { in: app/** }
  container:           { in: app/internal/container/** }
  commands:            { in: commands/* }
  services:            { in: services/** }
  view:                { in: view }
  models:              { in: models/** }
  libs:                { in: pkg/** }

commonVendors:
  - cli
  - sdk-models
  - go-x-libs

commonComponents:
  - models
  - libs

dependencies:
  main:
    mayDependOn:
      - container

  container:
    anyVendorDeps: true
    anyProjectDeps: true

  commands:
    canUse:
      - sdk-commands

  services:
    mayDependOn:
      - services
    canUse:
      - sdk-commands
      - sdk-libs
      - cli-term-libs

  view:
    canUse:
      - sdk-commands