version: 4
workingDirectory: internal

settings:
  imports:
    strictMode: false
    allowAnyVendorImports: false
  structTags:
    allowed: [json]

exclude:
  directories:
    - view/testcases

  files:
    - "^.*_test\\.go$"
    - "^.*\/test\/.*$"
    - "^.*\/tests\/.*$"

vendors:
  go-common:           { in: golang.org/x/sync/errgroup }
  go-ast:              { in: [ golang.org/x/mod/modfile, golang.org/x/tools/go/packages ] }
  3rd-code-highlight:  { in: github.com/alecthomas/chroma/* }
  3rd-graph:           { in: oss.terrastruct.com/d2/** }
  3rd-yaml:
    in:
      - github.com/goccy/go-yaml
      - github.com/goccy/go-yaml/**
      - github.com/fe3dback/go-yaml    # custom fork (need propose back PR)
      - github.com/fe3dback/go-yaml/** # custom fork (need propose back PR)

components:
  main:                { in: app }
  container:           { in: app/internal/container/** }
  commands:            { in: commands/* }
  operations:          { in: operations/* }
  services:            { in: services/** }
  view:                { in: view }
  models:              { in: models/** }
  libs:                { in: pkg/** }

commonVendors:
  - go-common

commonComponents:
  - models
  - libs

dependencies:
  main:
    mayDependOn:
      - container

  container:
    anyVendorDeps: true
    anyProjectDeps: true

  commands:
    mayDependOn:
      - operations

  operations:
    mayDependOn:
      - services
    canUse:
      - 3rd-graph
    canContainTags:
      - db

  services:
    mayDependOn:
      - services
    canUse:
      - go-ast
      - 3rd-yaml
      - 3rd-code-highlight
