version: 1

# ------------------------------------------------------------------
# Global settings
# ------------------------------------------------------------------
allow:
  depOnAnyVendor: false

# ------------------------------------------------------------------
# Excluded folders from analyse
# ------------------------------------------------------------------
exclude:
  - .idea
  - vendor

# ------------------------------------------------------------------
# Excluded files by regexp mask
# ------------------------------------------------------------------
excludeFiles:
  - "^.*_test\\.go$"

# ------------------------------------------------------------------
# Vendor libs
# ------------------------------------------------------------------
vendors:
  loader-yaml:
    in: gopkg.in/yaml.v2
  vectors:
    in: github.com/fe3dback/go-vec

# ------------------------------------------------------------------
# Project components
#
# Used for split real modules and packages to abstract thing
# ------------------------------------------------------------------
components:
  main:
    in: .
  engine:
    in: engine
  engine_vendor_events:
    in: engine/vendor/*/event
  game:
    in: game
  game_component:
    in: game/components/**
  utils:
    in: utils

# ------------------------------------------------------------------
# All components can import any packages from "common" list
# ------------------------------------------------------------------
commonComponents:
  - utils

# ------------------------------------------------------------------
# All components can import any vendors from "common" list
# ------------------------------------------------------------------
commonVendors:
  - vectors

# ------------------------------------------------------------------
# Dependency rules
# ------------------------------------------------------------------
deps:
  engine_vendor_events:
    mayDependOn:
      - engine
    canUse:
      - loader-yaml

  game:
    mayDependOn:
      - engine
      - game_component

  main:
    mayDependOn:
      - game
      - engine
